name: Build and Deploy ASP.NET to Somee

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Crear carpeta temporal de build
      run: |
      mkdir build
      robocopy . build /E /XD build
      shell: powershell


    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Descargar paquete necesario en carpeta accesible
      working-directory: build
      run: nuget install Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 4.1.0 -OutputDirectory ../packages

    - name: Restaurar paquetes NuGet en carpeta accesible
      working-directory: build
      run: nuget restore Prueba_NET_SQL.sln -PackagesDirectory ../packages

    - name: Verificar contenido de ../packages
      run: dir packages /s
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build ASP.NET app
      working-directory: build
      run: msbuild Prueba_NET_SQL.sln /p:Configuration=Release
      shell: cmd

    - name: Deploy to Somee via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build\bin\Release\
        server-dir: ${{ secrets.FTP_DESTINATION }}
